import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { MaxUI, Button, Panel, Typography } from '@maxhub/max-ui';
import '@maxhub/max-ui/dist/styles.css';
import './style.css';

const names = { staff: 'Штат', reserve: 'Резерв', youdo: 'YouDo — демо-модель', profi: 'Профи.ру — демо-модель' };
const states = { draft: 'Черновик', searching: 'Идёт поиск', unfilled: 'Пока не закрыта', awaiting_confirmation: 'Ожидаем подтверждения', confirmed: 'Подмена согласована', completed: 'Выход отмечен', cancelled: 'Отменена' };
const scenarios = { success: 'Успех', no_results: 'Нет откликов', decline: 'Отказ', source_error: 'Ошибка источника' };
const fmt = iso => new Intl.DateTimeFormat('ru-RU', { timeZone: 'Europe/Moscow', day: 'numeric', month: 'long', hour: '2-digit', minute: '2-digit' }).format(new Date(iso));
const localMoscow = date => { const parts = new Intl.DateTimeFormat('en-CA', { timeZone: 'Europe/Moscow', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).formatToParts(date); const p = Object.fromEntries(parts.map(x => [x.type, x.value])); return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`; };
const initForm = () => { const tomorrow = new Date(Date.now() + 86400000); const start = new Date(tomorrow); start.setUTCHours(6, 0, 0, 0); const end = new Date(start.getTime() + 8 * 3600000); return { siteId: '', role: 'Бариста', startsAt: localMoscow(start), endsAt: localMoscow(end), payRub: '6000', skills: ['Эспрессо'], description: '', decisionDeadline: localMoscow(new Date(start.getTime() - 12 * 3600000)), sources: ['staff', 'reserve', 'youdo', 'profi'] }; };
async function api(path, method = 'GET', body) { const res = await fetch('/api' + path, { method, credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Не удалось выполнить действие'); return data; }
function Action({ children, onClick, busy, variant = 'primary', disabled = false, className = '' }) { return <Button type="button" variant={variant} size="medium" className={className} onClick={onClick} disabled={busy || disabled}>{busy ? 'Подождите…' : children}</Button>; }
function Chip({ children, tone = '' }) { return <span className={`chip ${tone}`}>{children}</span>; }
function Heading({ eyebrow, title, subtitle }) { return <div className="heading"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div>; }

function App() {
  const [auth, setAuth] = useState('loading'); const [browserDemo, setBrowserDemo] = useState(false); const [business, setBusiness] = useState(null); const [sites, setSites] = useState([]); const [reserve, setReserve] = useState([]); const [shifts, setShifts] = useState([]);
  const [screen, setScreen] = useState('list'); const [tab, setTab] = useState('shifts'); const [detail, setDetail] = useState(null); const [detailTab, setDetailTab] = useState('responses'); const [candidateId, setCandidateId] = useState(null);
  const [form, setForm] = useState(initForm); const [scenario, setScenario] = useState('success'); const [statusFilter, setStatusFilter] = useState('all'); const [draftMessage, setDraftMessage] = useState(''); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  async function refresh(id) { const [b, l] = await Promise.all([api('/bootstrap'), api('/shifts')]); setBusiness(b.business); setSites(b.sites); setReserve(b.reserve); setShifts(l.shifts); if (id) setDetail(await api(`/shifts/${id}`)); }
  useEffect(() => { api('/config').then(config => setBrowserDemo(config.browserDemo)).catch(() => {}); (async () => { try { if (window.WebApp?.initData) await api('/auth/max', 'POST', { initData: window.WebApp.initData }); await refresh(); setAuth('ready'); } catch (e) { if (e.message.includes('через MAX') || e.message.includes('Сессия') || e.message.includes('данные MAX')) setAuth('login'); else { setError(e.message); setAuth('login'); } } })(); }, []);
  useEffect(() => { if (!detail || !['searching','awaiting_confirmation'].includes(detail.shift.status)) return; const timer = setInterval(() => { api(`/shifts/${detail.shift.id}`).then(setDetail).catch(() => {}); }, 15000); return () => clearInterval(timer); }, [detail?.shift.id, detail?.shift.status]);
  async function run(key, task, success) { if (busy) return; setBusy(key); setError(''); setNotice(''); try { const result = await task(); if (result?.shift) { setDetail(result); await refresh(result.shift.id); } else await refresh(detail?.shift.id); if (success) setNotice(success); return result; } catch (e) { setError(e.message); } finally { setBusy(''); } }
  async function login() { setBusy('login'); setError(''); try { await api('/auth/demo', 'POST', { persona: 'manager' }); await refresh(); setAuth('ready'); } catch (e) { setError(e.message); } finally { setBusy(''); } }
  async function createShift() { const payload = { ...form, siteId: Number(form.siteId), payRub: Number(form.payRub), startsAt: new Date(form.startsAt + ':00+03:00').toISOString(), endsAt: new Date(form.endsAt + ':00+03:00').toISOString(), decisionDeadline: new Date(form.decisionDeadline + ':00+03:00').toISOString(), scenario }; const result = await run('create', () => api('/shifts', 'POST', payload), 'Заявка создана. Проверьте условия и запустите поиск.'); if (result) { setScreen('detail'); setDetailTab('sources'); setCandidateId(null); } }
  function openShift(id) { setError(''); setNotice(''); setScreen('detail'); setTab('shifts'); setDetailTab('responses'); setCandidateId(null); api(`/shifts/${id}`).then(setDetail).catch(e => setError(e.message)); }
  function changeTab(value) { setTab(value); setScreen('list'); setError(''); setNotice(''); }
  const selected = detail?.responses.find(x => x.candidateId === candidateId);
  const visible = shifts.filter(s => statusFilter === 'all' || (statusFilter === 'active' ? !['completed','cancelled'].includes(s.status) : ['completed','cancelled'].includes(s.status)));
  if (auth === 'loading') return <div className="auth"><div className="brandmark">П</div><p>Открываем «Подмену»…</p></div>;
  if (auth === 'login') return <div className="auth"><div className="brandmark">П</div><h1>Подмена</h1><p>Откройте мини-приложение из чата бота MAX.{browserDemo && ' Для локальной проверки доступен отдельный тестовый вход.'}</p>{browserDemo && <Action onClick={login} busy={busy === 'login'}>Войти в локальное демо</Action>}{error && <div className="alert error">{error}</div>}</div>;
  return <div className="app-shell">
    <header className="topbar"><div className="topbar-inner"><div className="identity"><div className="brandmark small">П</div><div><strong>Подмена</strong><span>{business?.name}</span></div></div><div className="header-meta"><span>МОСКВА · МСК</span><Chip tone="demo">ДЕМО</Chip></div></div></header>
    <main className="layout"><aside className="sidebar"><nav aria-label="Разделы"><button className={tab === 'shifts' ? 'nav active' : 'nav'} onClick={() => changeTab('shifts')}><span>▦</span> Смены <em>{shifts.length}</em></button><button className={tab === 'reserve' ? 'nav active' : 'nav'} onClick={() => changeTab('reserve')}><span>◯</span> Резерв</button><button className={tab === 'demo' ? 'nav active' : 'nav'} onClick={() => changeTab('demo')}><span>⚙</span> Демо</button></nav><div className="sidebar-note"><b>Тестовая среда</b><p>Внешние площадки и кандидаты смоделированы.</p></div></aside>
      <div className="content"><div className="demo-banner"><span className="demo-dot"/> Демо: внешние площадки и кандидаты смоделированы</div>{error && <div className="alert error" role="alert">{error}<button onClick={() => setError('')} aria-label="Закрыть ошибку">×</button></div>}{notice && <div className="alert success" role="status">{notice}<button onClick={() => setNotice('')} aria-label="Закрыть уведомление">×</button></div>}
      {tab === 'shifts' && screen === 'list' && <><div className="page-head"><Heading eyebrow="УПРАВЛЕНИЕ СМЕНАМИ" title="Смены" subtitle="Заявки, отклики и согласованные выходы в одном месте."/><Action onClick={() => { setForm({ ...initForm(), siteId: String(sites[0]?.id || '') }); setScreen('create'); }}>+ Найти подмену</Action></div><div className="stats"><div><span>Всего заявок</span><strong>{shifts.length}</strong></div><div><span>В поиске</span><strong>{shifts.filter(x => ['searching','unfilled','awaiting_confirmation'].includes(x.status)).length}</strong></div><div><span>Согласовано</span><strong>{shifts.filter(x => ['confirmed','completed'].includes(x.status)).length}</strong></div></div><div className="filter-row"><button className={statusFilter === 'all' ? 'filter active' : 'filter'} onClick={() => setStatusFilter('all')}>Все</button><button className={statusFilter === 'active' ? 'filter active' : 'filter'} onClick={() => setStatusFilter('active')}>Активные</button><button className={statusFilter === 'done' ? 'filter active' : 'filter'} onClick={() => setStatusFilter('done')}>Завершённые</button></div><div className="list">{visible.length ? visible.map(s => <button className="shift-card" key={s.id} onClick={() => openShift(s.id)}><div className="shift-main"><div className="avatar">Б</div><div><strong>{s.role} · {s.site_name}</strong><span>{fmt(s.starts_at)} – {new Intl.DateTimeFormat('ru-RU', { timeZone: 'Europe/Moscow', hour: '2-digit', minute: '2-digit' }).format(new Date(s.ends_at))}</span><small>{s.site_address}</small></div></div><div className="shift-side"><Chip tone={s.status}>{states[s.status]}</Chip><b>{s.payRub.toLocaleString('ru-RU')} ₽</b></div></button>) : <div className="empty"><div className="empty-symbol">○</div><h3>Заявок пока нет</h3><p>Создайте первую смену, чтобы запустить поиск подмены.</p><Action onClick={() => { setForm({ ...initForm(), siteId: String(sites[0]?.id || '') }); setScreen('create'); }}>Найти подмену</Action></div>}</div></>}
      {tab === 'shifts' && screen === 'create' && <><button className="back" onClick={() => setScreen('list')}>← К списку смен</button><Heading eyebrow="НОВАЯ ЗАЯВКА" title="Найти подмену" subtitle="Укажите условия один раз. Поиск запустится после проверки заявки."/><div className="form-layout"><Panel mode="secondary" className="form-panel"><h2>Условия смены</h2><div className="field-grid"><label>Точка<select value={form.siteId} onChange={e => setForm({ ...form, siteId: e.target.value })}>{sites.map(s => <option key={s.id} value={s.id}>{s.name} · {s.address}</option>)}</select></label><label>Роль<select value={form.role} onChange={e => setForm({ ...form, role: e.target.value })}><option>Бариста</option></select></label><label>Начало · МСК<input type="datetime-local" value={form.startsAt} onChange={e => setForm({ ...form, startsAt: e.target.value })}/></label><label>Окончание · МСК<input type="datetime-local" value={form.endsAt} onChange={e => setForm({ ...form, endsAt: e.target.value })}/></label><label>Оплата человеку за смену · ₽<input type="number" min="1000" max="100000" value={form.payRub} onChange={e => setForm({ ...form, payRub: e.target.value })}/></label><label>Решение до · МСК<input type="datetime-local" value={form.decisionDeadline} onChange={e => setForm({ ...form, decisionDeadline: e.target.value })}/></label></div><div className="field-block"><b>Обязательные навыки</b><div className="check-row">{['Эспрессо','Касса','Латте-арт'].map(x => <label className="check" key={x}><input type="checkbox" checked={form.skills.includes(x)} onChange={e => setForm({ ...form, skills: e.target.checked ? [...form.skills,x] : form.skills.filter(y => y !== x) })}/>{x}</label>)}</div></div><label className="field-block">Описание<textarea rows="3" maxLength="500" placeholder="Например: опыт работы с потоком утром" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}/></label><div className="field-block"><b>Источники поиска</b><div className="check-row">{Object.entries(names).map(([key,label]) => <label className="check" key={key}><input type="checkbox" checked={form.sources.includes(key)} onChange={e => setForm({ ...form, sources: e.target.checked ? [...form.sources,key] : form.sources.filter(y => y !== key) })}/>{label}</label>)}</div></div></Panel><aside className="summary"><h3>Перед запуском</h3><p><span>Точка</span><b>{sites.find(x => String(x.id) === String(form.siteId))?.name || 'Не выбрана'}</b></p><p><span>Смена</span><b>{form.startsAt?.replace('T',' · ')} — {form.endsAt?.split('T')[1]} МСК</b></p><p><span>Оплата</span><b>{Number(form.payRub || 0).toLocaleString('ru-RU')} ₽ человеку</b></p><p><span>Источники</span><b>{form.sources.length}</b></p><div className="summary-note">Внешние отклики и подтверждения будут смоделированы.</div><Action className="full" onClick={createShift} busy={busy === 'create'}>Создать заявку</Action></aside></div></>}
      {tab === 'shifts' && screen === 'detail' && detail && <><button className="back" onClick={() => setScreen('list')}>← К списку смен</button><div className="detail-head"><div><div className="eyebrow">ЗАЯВКА №{detail.shift.id}</div><h1>{detail.shift.role} · {detail.shift.site_name}</h1><p>{fmt(detail.shift.starts_at)} · {detail.shift.site_address}</p></div><Chip tone={detail.shift.status}>{states[detail.shift.status]}</Chip></div><div className="detail-grid"><section className="detail-main"><div className="conditions"><div><span>Смена</span><strong>{fmt(detail.shift.starts_at)} – {new Intl.DateTimeFormat('ru-RU', { timeZone: 'Europe/Moscow', hour: '2-digit', minute: '2-digit' }).format(new Date(detail.shift.ends_at))}</strong></div><div><span>Оплата</span><strong>{detail.shift.payRub.toLocaleString('ru-RU')} ₽</strong></div><div><span>Навыки</span><strong>{detail.shift.skills.join(', ')}</strong></div><div><span>Решение до</span><strong>{fmt(detail.shift.decision_deadline)}</strong></div></div>{detail.shift.description && <p className="description">{detail.shift.description}</p>}<div className="tabs"><button className={detailTab === 'responses' ? 'active' : ''} onClick={() => setDetailTab('responses')}>Отклики <i>{detail.responses.length}</i></button><button className={detailTab === 'sources' ? 'active' : ''} onClick={() => setDetailTab('sources')}>Источники</button><button className={detailTab === 'attendance' ? 'active' : ''} onClick={() => setDetailTab('attendance')}>Выход</button></div>
      {detailTab === 'responses' && <>{detail.responses.length ? <div className="response-list">{detail.responses.map(r => <button className={candidateId === r.candidateId ? 'response active' : 'response'} key={r.id} onClick={() => setCandidateId(r.candidateId)}><span className="avatar person">{r.name[0]}</span><span className="response-info"><strong>{r.name}</strong><small>{names[r.source]}</small><em>{r.skills.join(' · ')}</em></span><span className="response-money">{r.rateRub.toLocaleString('ru-RU')} ₽ <span>→</span></span></button>)}</div> : <div className="empty compact"><h3>Подходящих откликов нет</h3><p>Заявка остаётся открытой. Проверьте источники или повторите поиск.</p></div>}{selected && <section className="candidate"><div className="candidate-head"><div><div className="eyebrow">ПРОФИЛЬ · {names[selected.source]}</div><h2>{selected.name}</h2><p>Заявленный опыт: {selected.experienceYears} г. · Доступность: {selected.available ? 'указана в демо-профиле' : 'не подтверждена'}</p></div><strong>{selected.rateRub.toLocaleString('ru-RU')} ₽</strong></div><div className="why"><b>Почему подходит</b>{selected.reasons.map(x => <p key={x}>✓ {x}</p>)}</div><h3>Переписка по заявке</h3><div className="messages">{detail.messages.filter(m => m.candidateId === selected.candidateId).length ? detail.messages.filter(m => m.candidateId === selected.candidateId).map(m => <div className={m.sender === 'manager' ? 'message own' : 'message'} key={m.id}><small>{m.sender === 'manager' ? 'Вы' : `${selected.name} · модельный ответ`}</small><p>{m.text}</p></div>) : <p className="muted">Сообщений пока нет. Уточните условия перед предложением.</p>}</div><div className="message-form"><input aria-label="Сообщение кандидату" placeholder="Написать сообщение…" value={draftMessage} maxLength="1000" onChange={e => setDraftMessage(e.target.value)}/><Action variant="secondary" busy={busy === 'message'} disabled={!draftMessage.trim()} onClick={async () => { const value = draftMessage; const result = await run('message', () => api(`/shifts/${detail.shift.id}/messages`, 'POST', { candidateId, text: value }), 'Сообщение сохранено'); if (result) setDraftMessage(''); }}>Отправить</Action></div>{detail.shift.status === 'searching' && <div className="candidate-action"><p>Предложение зафиксирует место, время и оплату. Смена будет согласована только после отдельного подтверждения.</p><Action busy={busy === 'offer'} onClick={() => run('offer', () => api(`/shifts/${detail.shift.id}/offer`, 'POST', { candidateId }), 'Предложение отправлено. Ожидаем подтверждения.')}>Предложить смену</Action></div>}</section>}</>}
      {detailTab === 'sources' && <div className="sources">{detail.shift.sources.map(s => { const pub = detail.publications.find(x => x.source === s); return <div className="source" key={s}><span className="source-icon">{s[0].toUpperCase()}</span><div><strong>{names[s]}</strong><small>{pub?.detail || 'Поиск ещё не запускался'}</small></div><Chip tone={pub?.status || 'draft'}>{pub?.status === 'failed' ? 'Ошибка' : pub?.status === 'sent' ? 'Обращение создано' : pub?.status === 'closed' ? 'Закрыто' : 'Не запущено'}</Chip></div>; })}</div>}
      {detailTab === 'attendance' && <div className="attendance">{detail.offer ? <><div className="confirmed-person"><div className="avatar person">{detail.offer.name[0]}</div><div><strong>{detail.offer.name}</strong><p>{detail.offer.status === 'pending' ? 'Предложение отправлено, ждём отдельного ответа' : detail.offer.status === 'confirmed' ? 'Демо-кандидат подтвердил условия' : 'Предложение отменено или отклонено'}</p></div></div><div className="terms"><p>Место: <b>{detail.offer.siteName}</b></p><p>Время: <b>{fmt(detail.offer.startsAt)}</b></p><p>Оплата человеку: <b>{detail.offer.payRub.toLocaleString('ru-RU')} ₽</b></p></div>{detail.shift.status === 'awaiting_confirmation' && <div className="action-row"><Action busy={busy === 'confirm'} onClick={() => run('confirm', () => api(`/shifts/${detail.shift.id}/demo-decision`, 'POST', { decision: 'confirm' }), 'Демо-кандидат подтвердил выход')}>Демо: кандидат подтвердил</Action><Action variant="secondary" busy={busy === 'decline'} onClick={() => run('decline', () => api(`/shifts/${detail.shift.id}/demo-decision`, 'POST', { decision: 'decline' }), 'Демо-кандидат отказался. Поиск продолжается.')}>Демо: кандидат отказался</Action></div>}{detail.shift.status === 'confirmed' && <><div className="action-row"><Action busy={busy === 'arrived'} onClick={() => run('arrived', () => api(`/shifts/${detail.shift.id}/attendance`, 'POST', { value: 'arrived' }), 'Выход отмечен как тестовое событие')}>Отметить выход</Action><Action variant="secondary" busy={busy === 'no_show'} onClick={() => run('no_show', () => api(`/shifts/${detail.shift.id}/attendance`, 'POST', { value: 'no_show' }), 'Невыход отмечен как тестовое событие')}>Отметить невыход</Action></div><p className="muted">Отметка выхода — действие управляющего, не проверка фактической явки платформой.</p></>}{['confirmed','completed'].includes(detail.shift.status) && <Action variant="secondary" busy={busy === 'reserve'} onClick={() => run('reserve', () => api(`/shifts/${detail.shift.id}/reserve`, 'POST', { candidateId: detail.offer.candidateId }), 'Человек сохранён в резерв')}>Добавить в резерв</Action>}</> : <div className="empty compact"><h3>Кандидат ещё не выбран</h3><p>После предложения и отдельного подтверждения здесь появятся согласованные условия.</p></div>}</div>}
      </section><aside className="detail-aside"><Panel mode="secondary" className="process"><h3>Ход подмены</h3>{[['created','Заявка'],['search','Поиск'],['offer','Предложение'],['confirm','Подтверждение'],['arrived','Выход']].map(([key,label],i) => <div className="step" key={key}><span className={detail.events.some(e => e.kind === key || (key === 'confirm' && e.kind === 'confirm')) ? 'done' : ''}>{i+1}</span>{label}</div>)}<div className="step-note">Согласие на смену и фактический выход — разные этапы.</div></Panel>{['draft','unfilled','searching'].includes(detail.shift.status) && <Action className="full" busy={busy === 'search'} onClick={() => run('search', () => api(`/shifts/${detail.shift.id}/search`, 'POST', {}), 'Поиск выполнен. Проверьте статусы источников и отклики.')}>{detail.shift.status === 'draft' ? 'Запустить поиск' : 'Повторить поиск'}</Action>}{!['cancelled','completed'].includes(detail.shift.status) && <Action className="full" variant="secondary" busy={busy === 'cancel'} onClick={() => run('cancel', () => api(`/shifts/${detail.shift.id}/cancel`, 'POST', {}), 'Заявка отменена')}>Отменить заявку</Action>}<div className="history"><h3>История</h3>{detail.events.slice(0,5).map((e,i) => <p key={i}><small>{fmt(e.createdAt)}</small>{e.text}</p>)}</div></aside></div></>}
      {tab === 'reserve' && <><Heading eyebrow="ВАШИ КОНТАКТЫ" title="Резерв" subtitle="Кандидаты, которых вы сохранили после согласованной смены."/><div className="reserve-list">{reserve.length ? reserve.map(p => <div className="reserve-card" key={p.id}><span className="avatar person">{p.name[0]}</span><div><strong>{p.name}</strong><small>{names[p.source]} · {p.skills.join(', ')}</small></div><b>{p.rateRub.toLocaleString('ru-RU')} ₽</b></div>) : <div className="empty"><h3>Резерв пока пуст</h3><p>После согласованной смены добавьте человека сюда для повторного приглашения.</p></div>}</div></>}
      {tab === 'demo' && <><Heading eyebrow="НАСТРОЙКИ ПРОВЕРКИ" title="Демо-сценарии" subtitle="Выберите поведение следующей заявки. Источники и ответы здесь тестовые."/><div className="scenario-grid">{Object.entries(scenarios).map(([key,label]) => <button key={key} className={scenario === key ? 'scenario active' : 'scenario'} onClick={() => setScenario(key)}><span className="radio"/><strong>{label}</strong><small>{key === 'success' ? 'Есть подходящие отклики' : key === 'no_results' ? 'Никто не подходит' : key === 'decline' ? 'Можно воспроизвести отказ' : 'Профи.ру недоступен, другие источники работают'}</small></button>)}</div><Panel mode="secondary" className="demo-control"><h3>Сброс тестовых данных</h3><p>Удалит только ваши заявки, переписки и резерв в текущем демо-пространстве.</p><Action variant="destructive" busy={busy === 'reset'} onClick={() => { if (window.confirm('Сбросить ваши тестовые данные?')) run('reset', () => api('/demo/reset', 'POST', {}), 'Ваши тестовые данные сброшены'); }}>Сбросить мои данные</Action></Panel></>}
      </div></main><nav className="mobile-nav" aria-label="Разделы"><button className={tab === 'shifts' ? 'active' : ''} onClick={() => changeTab('shifts')}><span>▦</span>Смены</button><button className={tab === 'reserve' ? 'active' : ''} onClick={() => changeTab('reserve')}><span>◯</span>Резерв</button><button className={tab === 'demo' ? 'active' : ''} onClick={() => changeTab('demo')}><span>⚙</span>Демо</button></nav></div>;
}

createRoot(document.getElementById('root')).render(<MaxUI><App/></MaxUI>);
